### ISSUE TITLE
Verificação grupo 3

### ISSUE THREAD

**Issue by brenob6** [Requisitos-de-Software/2023.2-Carteira_Digital_de_Transito#41]
# Planejamento

- [x] Padronização do projeto
- [x] Rich Picture
- [x] Aplicativo selecionado
- [x] Cronogramas
- [x] Ferramentas de Uso
- [x] Heatmap
- [x] Termos de Uso
- [x] Personas

# Técnicas

- [x] Brainstorming
- [x] Introspecção
- [x] Observação
- [x] Questionário

# Priorização de requisitos

- [x] $100
- [x] Introdução
- [x] Moscow
- [x] Three Level Scale
- [x] Cenários
- [x] Léxicos
- [x] Casos de uso
- [x] Especificação Suplementar

# Modelagem Ágil

- [x] Backlog do produto
- [x] Histórias de Usuário
- [x] NFR Framework

**Comment by LimirioGuimaraes** [comment]
Para iniciar, ficarei responsável pela verificação dos artefatos que apresentam técnicas de elicitação de requisitos.

**Comment by Mayara-tech** [comment]
Ficarei responsável por 4 tarefas do planejamento (padronização, rich picture, aplicativo selecionado, cronograma ) e duas tecnicas de priorização, cenários e Three level scale

**Comment by yabamiah** [comment]
Ficarei responsável pela Personas, Análise de atividades e Casos de uso.

**Comment by brenob6** [comment]
Vou fazer a especificação suplementar.

**Comment by yabamiah** [comment]
Vou fazer da técnica de priorização moscow

**Comment by MilenaBaruc** [comment]
Ficarei responsável por: Padronização do projeto, Ferramentas de uso, $100 e Introdução (priorização de req.)

**Comment by LuisMiranda10** [comment]
Ficarei responsável por Aplicativo selecionado, Heatmap e Termos de Uso.
