### ISSUE TITLE
Verificação 

### ISSUE THREAD

**Issue by Mayara-tech** [Requisitos-de-Software/2023.2-Carteira_Digital_de_Transito#55]
# Planejamento

- [x] Aplicativo selecionado
- [x] Cronograma
- [x] Ferramentas 
- [x] Heatmap
- [x] Politicas
- [x] Metodologia

# Pré-rastreabilidade
- [x] RichPicture

# Elicitação 
- [x] Personas
### Definição do perfil de usuário
- [x] Questionário
- [x] Documentação
- [x] perfil de usuário
### Elicitação de requisitos
- [x]  Storyboard
- [x]  Glossáro
- [x]  Entrevista
- [x]  Introspecção
- [x] Requisitos elicitados
### Priorização de requisitos
- [x] First Things First
- [x] $100
- [ ]  Three Level Scale

# Modelagem
- [x]  Cenários
- [x]  Léxicos
- [x]  Casos de uso
- [x]  Especificação Suplementar

### Modelagem Ágil
- [x]  Backlog do produto
- [x]  Histórias de Usuário
- [ ]  NFR Framework

# Rastreabilidade
- [ ] Pós rastreabilidade
- [x] Matriz geral

**Comment by Mayara-tech** [comment]
Mayara e Limirio 
Politicas
Metodologia
Rich picture
Storyboard
Glossáro
First Things First
Lexicos
Histórias de usuários

**Comment by brenob6** [comment]
Breno 
Planejamento - Ferramentas
Elicitação - Personas
Modelagem Ágil - Backlog

**Comment by yabamiah** [comment]
Vinicius, Luis e Altino

Heatmap
Aplicativo selecionado
Perfil de usuário
Questionário
Introspecção
Requisitos elicitados
100$
Cenários
Casos de uso
Matriz Geral
NFR Framework
Especificação

**Comment by MilenaBaruc** [comment]
cronograma - planejamento 
documentação - Definição do perfil de usuário
entrevista - Elicitação de requisitos
Especificação Suplementar - modelagem
